/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbolproyekuts2;

import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class TransaksiBaru extends javax.swing.JFrame {
    
    private String kamarTerpilih;
    
    public TransaksiBaru() {
        initComponents();
        
    }
    
    public TransaksiBaru(String kamar) {
        this.kamarTerpilih = kamar; // Simpan nomor kamar yang dipilih
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglCheckIn = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oke = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        checkIn = new com.toedter.calendar.JDateChooser();
        checkOut = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalBiayaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cashButton = new javax.swing.JButton();
        qrisButton = new javax.swing.JButton();

        tglCheckIn.setBackground(new java.awt.Color(255, 255, 255));
        tglCheckIn.setForeground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tanggal Check-in");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tanggal Check-out");

        oke.setBackground(new java.awt.Color(255, 255, 255));
        oke.setForeground(new java.awt.Color(0, 0, 0));
        oke.setText("Oke");
        oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeActionPerformed(evt);
            }
        });

        kembali.setBackground(new java.awt.Color(255, 255, 255));
        kembali.setForeground(new java.awt.Color(0, 0, 0));
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        checkIn.setBackground(new java.awt.Color(255, 255, 255));
        checkIn.setForeground(new java.awt.Color(0, 0, 0));
        checkIn.setDateFormatString("dd-MM-yyyy");
        checkIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkInPropertyChange(evt);
            }
        });

        checkOut.setBackground(new java.awt.Color(255, 255, 255));
        checkOut.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setText("Total Biaya : ");

        totalBiayaField.setBackground(new java.awt.Color(255, 255, 255));
        totalBiayaField.setForeground(new java.awt.Color(0, 0, 0));
        totalBiayaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBiayaFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Pilih Metode Pembayaran :");

        cashButton.setBackground(new java.awt.Color(255, 255, 255));
        cashButton.setForeground(new java.awt.Color(0, 0, 0));
        cashButton.setText("CASH");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });

        qrisButton.setBackground(new java.awt.Color(255, 255, 255));
        qrisButton.setForeground(new java.awt.Color(0, 0, 0));
        qrisButton.setText("QRIS");
        qrisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(totalBiayaField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qrisButton)
                            .addComponent(cashButton))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalBiayaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cashButton))
                .addGap(18, 18, 18)
                .addComponent(qrisButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kembali))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(checkIn, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oke)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oke)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kembali)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeActionPerformed
        
        Date checkInDate = checkIn.getDate();
        Date checkOutDate = checkOut.getDate();
        
        if (checkInDate != null && checkOutDate != null) {
            
            prosesPembayaran(kamarTerpilih, checkInDate, checkOutDate);
            
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih tanggal check-in dan check-out.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_okeActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Pembayaran langsung ke hotel \n Terima Kasih");
        dispose();
        
    }//GEN-LAST:event_cashButtonActionPerformed

    private void qrisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrisButtonActionPerformed
        
        JFrame qrFrame = new JFrame("QRIS Payment");
        qrFrame.setSize(300, 300);
        qrFrame.setLayout(new java.awt.BorderLayout());
        
        JLabel qrLabel = new JLabel("QR CODE AREA", SwingConstants.CENTER);
        qrLabel.setBorder(BorderFactory.createTitledBorder("Silakan Scan QR"));
        
        JLabel timerLabel = new JLabel("Timer: 0:60", SwingConstants.CENTER);
        
        qrFrame.add(qrLabel, java.awt.BorderLayout.CENTER);
        qrFrame.add(timerLabel, java.awt.BorderLayout.SOUTH);
        
        qrFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        qrFrame.setVisible(true);
        
        Timer timer = new Timer();
        final int[] timeLeft = {10};
        
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                timeLeft[0]--;
                timerLabel.setText("Timer: " + (timeLeft[0] / 60) + ":" + String.format("%02d", timeLeft[0] % 60));
                
                if (timeLeft[0] <= 0) {
                    timer.cancel();
                    timerLabel.setText("Waktu habis. Silakan ulangi.");
                    qrFrame.dispose();
                    JOptionPane.showMessageDialog(null,
                            "Waktu pembayaran sudah habis. silahkan ulangi pembayarannya", "peringatan!!!", JOptionPane.WARNING_MESSAGE);
                }
            }
        };
        
        timer.scheduleAtFixedRate(task, 0, 1000);
    }//GEN-LAST:event_qrisButtonActionPerformed

    private void totalBiayaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBiayaFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalBiayaFieldActionPerformed

    private void checkInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkInPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            
        }
    }//GEN-LAST:event_checkInPropertyChange
    private void prosesPembayaran(String kamar, Date checkInDate, Date checkOutDate) {
        int hargaKamar = getHargaKamar(kamarTerpilih);
        long lamaMenginap = (checkOutDate.getTime() - checkInDate.getTime()) / (1000 * 60 * 60 * 24); // Menghitung lama menginap dalam hari

        System.out.println("Kamar: " + kamar);
        System.out.println("Harga Kamar: " + hargaKamar);
        System.out.println("Lama Menginap: " + lamaMenginap);
        System.out.println(" ");
        
        
        if (lamaMenginap > 0) {
            int totalBiaya = (int) (lamaMenginap * hargaKamar);
            System.out.println("Total Biaya: " + totalBiaya);
            totalBiayaField.setText(String.valueOf(totalBiaya));
            if (totalBiaya > 0) {
                JOptionPane.showMessageDialog(this, "Total biaya untuk " + kamar + " adalah: " + totalBiaya, "Pembayaran", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(this, "Total biaya tidak boleh nol.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tanggal check-out harus setelah tanggal check-in.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        totalBiayaField.setEditable(false);
    }
    
    private int getHargaKamar(String kamar) {
        switch (kamar) {
            case "001":
                return 250000;
            case "002":
                return 250000; // Pastikan harga ditetapkan
            case "003":
                return 250000;
            case "004":
                return 350000;
            case "005":
                return 350000;
            case "006":
                return 350000;
            case "007":
                return 500000;
            case "008":
                return 500000;
            case "009":
                return 500000;
            default:
                return 0; // Pastikan tidak ada kamar yang tidak terdaftar
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TransaksiBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashButton;
    private com.toedter.calendar.JDateChooser checkIn;
    private com.toedter.calendar.JDateChooser checkOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembali;
    private javax.swing.JButton oke;
    private javax.swing.JButton qrisButton;
    private javax.swing.JTextField tglCheckIn;
    private javax.swing.JTextField totalBiayaField;
    // End of variables declaration//GEN-END:variables
}
